CREATE TABLE gestacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   gestante_id BIGINT NOT NULL,
   consumo_alcool BOOLEAN NOT NULL,
   frequencia_uso_alcool INT NOT NULL,
   data_ultima_menstruacao TIMESTAMP NOT NULL,
   data_inicio_gestacao TIMESTAMP NOT NULL,
   fator_rh VARCHAR(255) NOT NULL,
   fuma BOOLEAN NOT NULL,
   quantidade_cigarros_dia INT NOT NULL,
   uso_drogas INT NOT NULL,
   gravidez_planejada BOOLEAN NOT NULL,
   grupo_sanguineo INT NOT NULL,
   peso_antes_gestacao DECIMAL NOT NULL,
   risco_gestacional INT NOT NULL,
   vacina_hepatiteb BOOLEAN NOT NULL,
   situacao_gestacional INT NOT NULL,
   CONSTRAINT pk_gestacao PRIMARY KEY (id)
);

ALTER TABLE gestacao ADD CONSTRAINT FK_GESTACAO_ON_GESTANTE FOREIGN KEY (gestante_id) REFERENCES gestante (id);