CREATE TABLE acompanhamento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   gestante_id BIGINT NOT NULL,
   data_acompanhamento TIMESTAMP NOT NULL,
   realizado_por VARCHAR(255) NOT NULL,
   peso_atual DECIMAL NOT NULL,
   idade_gestacional INT NOT NULL,
   pressao_arterial VARCHAR(255) NOT NULL,
   batimentos_cardiacos_feto INT,
   altura_uterina INT,
   tipo VARCHAR(255) NOT NULL,
   CONSTRAINT pk_acompanhamento PRIMARY KEY (id)
);

ALTER TABLE acompanhamento ADD CONSTRAINT FK_ACOMPANHAMENTO_ON_GESTANTE FOREIGN KEY (gestante_id) REFERENCES gestante (id);