CREATE TABLE dadosativos (
  id BIGINT AUTO_INCREMENT NOT NULL,
   gestante_id BIGINT NULL,
   municipio VARCHAR(255) NOT NULL,
   diagnostico_desnutricao INT NOT NULL,
   energia_eletrica_domicilio BIT NOT NULL,
   escolaridade INT NOT NULL,
   tipo_moradia INT NOT NULL,
   moradia_rede_esgoto BIT NOT NULL,
   renda_familiar DECIMAL NOT NULL,
   tratamento_agua BIT NOT NULL,
   amamentacao BIT NOT NULL,
   chefe_familia VARCHAR(255) NOT NULL,
   data_ultima_gestacao datetime NULL,
   em_risco BIT NOT NULL,
   estado_civil INT NOT NULL,
   quantidade_abortos INT NOT NULL,
   quantidade_filhos_vivos INT NOT NULL,
   quantidade_gestacao INT NOT NULL,
   quantidade_nascidos_mortos INT NOT NULL,
   quantidade_nascidos_vivos INT NOT NULL,
   quantidade_obitos_semana1 INT NOT NULL,
   quantidade_obitos_apos_semana1 INT NOT NULL,
   quantidade_partos INT NOT NULL,
   quantidade_partos_cesarios INT NOT NULL,
   quantidade_partos_vaginais INT NOT NULL,
   quantidade_rn_peso2500_4000 INT NOT NULL,
   quantidade_rn_peso_maior4000 INT NOT NULL,
   quantidade_rn_peso_menor2500 INT NOT NULL,
   hipertensao BIT NOT NULL,
   diabetes BIT NOT NULL,
   cirurgia_pelvica BIT NOT NULL,
   infeccao_urinaria BIT NOT NULL,
   ma_formacao_congenita BIT NOT NULL,
   familiar_gemeos BIT NOT NULL,
   contato VARCHAR(255) NOT NULL,
   contato_emergencia VARCHAR(255) NOT NULL,
   CONSTRAINT `pk_dados-ativos` PRIMARY KEY (id)
);

ALTER TABLE `dadosativos` ADD CONSTRAINT `FK_DADOS-ATIVOS_ON_GESTANTE` FOREIGN KEY (gestante_id) REFERENCES gestante (id);